// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.webSQL.Models
{
    public partial class account_list_buildingsResult
    {
        public string BLDG_CDE { get; set; }
        public string BUILDING_DESC { get; set; }
    }
}
