// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.webSQL.Models
{
    [Table("account_profile")]
    public partial class account_profile
    {
        [Key]
        public int account_id { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string phone_pub { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string phone_priv { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string building_code { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string room { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string mailstop { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string department { get; set; }
        [StringLength(12)]
        [Unicode(false)]
        public string supervisor_id { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string today_events { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string future_events { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string mylinks { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string dining_menus { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string world_news { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string weather { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string systems { get; set; }
        [Required]
        [StringLength(1024)]
        [Unicode(false)]
        public string leftmodules { get; set; }
        [Required]
        [StringLength(1024)]
        [Unicode(false)]
        public string rightmodules { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string comment { get; set; }
        /// <summary>
        /// Display Who&apos;s Who Picture (Y/N)
        /// </summary>
        [StringLength(1)]
        [Unicode(false)]
        public string Show_Pic { get; set; }
        /// <summary>
        /// Chapel Credit Exception Value
        /// </summary>
        public byte? CHException { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime? Updated_On { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Updated_By { get; set; }
        [StringLength(75)]
        [Unicode(false)]
        public string office_hours { get; set; }
        [StringLength(30)]
        [Unicode(false)]
        public string relationship { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Pref_Pic_Exists { get; set; }
        [StringLength(2000)]
        [Unicode(false)]
        public string GCSA_Bio { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime? dt_last_login { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string last_ip_address { get; set; }
        [StringLength(350)]
        [Unicode(false)]
        public string Last_UserAgnt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LifeAndConduct_date { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string LifeAndConduct_answer { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string LifeAndConduct_reservations { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string campus_events { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string athletic_events { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string ID_Pic_Exists { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string BC_Pic_Exists { get; set; }
    }
}