// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.webSQL.Models
{
    [Index("code", Name = "NonClusteredIndex-Code", IsUnique = true)]
    public partial class Mailstop
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string code { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string description { get; set; }
        [StringLength(25)]
        [Unicode(false)]
        public string bldg_cde { get; set; }
    }
}