// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Table("AffiliationPoints", Schema = "RecIM")]
    public partial class AffiliationPoints
    {
        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string AffiliationName { get; set; }
        [Key]
        public int ActivityID { get; set; }

        [ForeignKey("AffiliationName")]
        [InverseProperty("AffiliationPoints")]
        public virtual Affiliations AffiliationNameNavigation { get; set; }
    }
}