// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Table("Affiliation", Schema = "RecIM")]
    public partial class Affiliation
    {
        public Affiliation()
        {
            Team = new HashSet<Team>();
        }

        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }

        [InverseProperty("AffiliationNavigation")]
        public virtual ICollection<Team> Team { get; set; }
    }
}