// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("Match", Schema = "RecIM")]
public partial class Match
{
    [Key]
    public int ID { get; set; }

    public int SeriesID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartTime { get; set; }

    public int SurfaceID { get; set; }

    public int StatusID { get; set; }

    [InverseProperty("Match")]
    public virtual MatchBracket MatchBracket { get; set; }

    [InverseProperty("Match")]
    public virtual ICollection<MatchParticipant> MatchParticipant { get; set; } = new List<MatchParticipant>();

    [InverseProperty("Match")]
    public virtual ICollection<MatchTeam> MatchTeam { get; set; } = new List<MatchTeam>();

    [ForeignKey("SeriesID")]
    [InverseProperty("Match")]
    public virtual Series Series { get; set; }

    [ForeignKey("StatusID")]
    [InverseProperty("Match")]
    public virtual MatchStatus Status { get; set; }

    [ForeignKey("SurfaceID")]
    [InverseProperty("Match")]
    public virtual Surface Surface { get; set; }
}