// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("MatchTeamStatus", Schema = "RecIM")]
public partial class MatchTeamStatus
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(64)]
    [Unicode(false)]
    public string Description { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<MatchTeam> MatchTeam { get; set; } = new List<MatchTeam>();
}