// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Keyless]
public partial class SeriesTeamView
{
    public int ID { get; set; }

    public int TeamID { get; set; }

    public int SeriesID { get; set; }

    public int WinCount { get; set; }

    public int LossCount { get; set; }

    public int TieCount { get; set; }

    [Column(TypeName = "decimal(38, 6)")]
    public decimal? SportsmanshipRating { get; set; }
}