// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Table("SeriesType", Schema = "RecIM")]
    public partial class SeriesType
    {
        public SeriesType()
        {
            Series = new HashSet<Series>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(256)]
        [Unicode(false)]
        public string Description { get; set; }
        [Required]
        [StringLength(4)]
        [Unicode(false)]
        public string TypeCode { get; set; }

        [InverseProperty("Type")]
        public virtual ICollection<Series> Series { get; set; }
    }
}