// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Gordon360.Models.MyGordon;

namespace Gordon360.Database.MyGordon
{
    public partial class MyGordonContext : DbContext
    {
        public MyGordonContext()
        {
        }

        public MyGordonContext(DbContextOptions<MyGordonContext> options)
            : base(options)
        {
        }

        public virtual DbSet<StudentNews> StudentNews { get; set; }
        public virtual DbSet<StudentNewsCategory> StudentNewsCategory { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=AdminTrainSQL;Initial Catalog=MyGordon;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<StudentNews>(entity =>
            {
                entity.Property(e => e.Accepted).HasDefaultValueSql("(0)");

                entity.Property(e => e.Entered).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Sent).HasDefaultValueSql("(0)");

                entity.Property(e => e.thisPastMailing).HasDefaultValueSql("(0)");

                entity.HasOne(d => d.category)
                    .WithMany(p => p.StudentNews)
                    .HasForeignKey(d => d.categoryID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_StudentNews_StudentNewsCategory");
            });

            modelBuilder.Entity<StudentNewsCategory>(entity =>
            {
                entity.Property(e => e.SortOrder).HasDefaultValueSql("(999)");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}