# Tell Travis what language to compile in
language: csharp

# Use Windows for the build since the API runs in IIS
os: windows

# Do not use Mono
mono: none

# Install NuGet, then build the solution
script:
  - choco install nuget.commandline
  - choco install visualstudio2017-workload-manageddesktop
  - choco install visualstudio2017-workload-netweb
  - scripts/build.bat

deploy:
  # Deploy develop to the staging environment
  - provider: script
    # Don't delete built application because we need it for deployment
    skip_cleanup: true
    script: scripts/deploy.bat
    on:
      branch: develop

  # Deploy master to production
  - provider: script
    # Don't delete built application because we need it for deployment
    skip_cleanup: true
    script: scripts/deploy.bat
    on:
      branch: master

# Only send notification emails on build failure
notifications:
  email:
    on_success: never
