//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCT_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Info
    {
        public string ACT_CDE { get; set; }
        public string ACT_DESCR { get; set; }
        public string MTG_DAY { get; set; }
        public Nullable<System.TimeSpan> MTG_TIME { get; set; }
        public string ACT_IMAGE { get; set; }
    }
}
