//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCT_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPERVISOR
    {
        public int SUP_ID { get; set; }
        public string ID_NUM { get; set; }
        public string ACT_CDE { get; set; }
        public string USER_NAME { get; set; }
        public string JOB_NAME { get; set; }
        public Nullable<System.DateTime> JOB_TIME { get; set; }
        public string SESSION_CDE { get; set; }
    }
}
