// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.CCT
{
    public partial class ADVISOR_SEPARATEResult
    {
        public int Advisor1 { get; set; }
        public int Advisor2 { get; set; }
        public int Advisor3 { get; set; }
    }
}
