// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Keyless]
public partial class Dining_Meal_Plan_Id_Mapping
{
    [Required]
    [StringLength(6)]
    [Unicode(false)]
    public string meal_plan_id { get; set; }

    [Required]
    [StringLength(2)]
    [Unicode(false)]
    public string meal_choice_id { get; set; }
}