// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Table("FacStaff_Field_Type", Schema = "dbo")]
    public partial class FacStaff_Field_Type
    {
        public int ID { get; set; }
        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string Field { get; set; }
    }
}