// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Table("FacStaff_Privacy", Schema = "dbo")]
    public partial class FacStaff_Privacy
    {
        [Key]
        [StringLength(10)]
        [Unicode(false)]
        public string gordon_id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Field { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Viewer { get; set; }
    }
}