// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.CCT
{
    public partial class GET_AA_APPLICATIONS_BY_IDResult
    {
        public int HousingAppID { get; set; }
        public DateTime? DateSubmitted { get; set; }
        public DateTime DateModified { get; set; }
        public string EditorUsername { get; set; }
    }
}
