// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.CCT
{
    public partial class GET_SINGLE_MESSAGE_BY_IDResult
    {
        public string message_id { get; set; }
        public string text { get; set; }
        public DateTime createdAt { get; set; }
        public string user_id { get; set; }
        public byte[] image { get; set; }
        public byte[] video { get; set; }
        public byte[] audio { get; set; }
        public bool system { get; set; }
        public bool sent { get; set; }
        public bool received { get; set; }
        public bool pending { get; set; }
    }
}
