// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.CCT
{
    public partial class GET_ROOM_BY_IDResult
    {
        public int room_id { get; set; }
        public string name { get; set; }
        public bool group { get; set; }
        public DateTime createdAt { get; set; }
        public DateTime lastupdated { get; set; }
        public byte[] roomImage { get; set; }
    }
}
