// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    public partial class Health_Status
    {
        [Key]
        public int ID_Num { get; set; }
        public byte HealthStatusID { get; set; }
        [Key]
        public DateTime Created { get; set; }
        public DateTime? Expires { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string CreatedBy { get; set; }
        public DateTime? Emailed { get; set; }
        [Unicode(false)]
        public string Notes { get; set; }

        [ForeignKey("HealthStatusID")]
        [InverseProperty("Health_Status")]
        public virtual Health_Status_CTRL HealthStatus { get; set; }
    }
}