// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

public partial class Poster
{
    [Key]
    public int ID { get; set; }

    [StringLength(8)]
    [Unicode(false)]
    public string ACT_CDE { get; set; }

    [Required]
    [StringLength(64)]
    [Unicode(false)]
    public string Title { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string Description { get; set; }

    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string ImagePath { get; set; }

    public DateTime VisibleDate { get; set; }

    public DateTime ExpirationDate { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string UploaderADUsername { get; set; }

    public int StatusID { get; set; }

    public int Priority { get; set; }

    [ForeignKey("ACT_CDE")]
    [InverseProperty("Poster")]
    public virtual ACT_INFO ACT_CDENavigation { get; set; }

    [ForeignKey("StatusID")]
    [InverseProperty("Poster")]
    public virtual PosterStatus Status { get; set; }
}