// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

public partial class PostedItem
{
    [Key]
    public int ItemId { get; set; } // Primary key for the item

    [Required]
    [StringLength(9)]
    [Unicode(false)]
    public string UserId { get; set; } // ID of the user who posted the item

    public DateTime PostDate { get; set; } // Date the item was posted

    [Required]
    [StringLength(50)]
    [Unicode(true)]
    public string ItemName { get; set; } // Name of the item

    public int ItemPrice { get; set; } // Price of the item

    [Required]
    [StringLength(20)]
    [Unicode(true)]
    public string ItemCategory { get; set; } // Category of the item

    [StringLength(300)]
    [Unicode(true)]
    public string ItemDetail { get; set; } // Detailed description of the item

    [Required]
    [StringLength(20)]
    [Unicode(true)]
    public string Condition { get; set; } // Condition of the item (e.g., new, used)

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string ItemStatus { get; set; } // Status of the item (e.g., available, sold)

    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string ImagePath1 { get; set; } // Path to the first image

    [StringLength(256)]
    [Unicode(false)]
    public string ImagePath2 { get; set; } // Path to the second image (nullable)

    [StringLength(256)]
    [Unicode(false)]
    public string ImagePath3 { get; set; } // Path to the third image (nullable)
}