// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("REQUEST", Schema = "dbo")]
public partial class REQUEST
{
    [Key]
    public int REQUEST_ID { get; set; }

    [Required]
    [StringLength(8)]
    [Unicode(false)]
    public string SESS_CDE { get; set; }

    [Required]
    [StringLength(8)]
    [Unicode(false)]
    public string ACT_CDE { get; set; }

    public int ID_NUM { get; set; }

    [Required]
    [StringLength(5)]
    [Unicode(false)]
    public string PART_CDE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DATE_SENT { get; set; }

    [StringLength(45)]
    [Unicode(false)]
    public string COMMENT_TXT { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string STATUS { get; set; }
}