// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Keyless]
    public partial class ScheduleTerm
    {
        [Required]
        [StringLength(4)]
        [Unicode(false)]
        public string YearCode { get; set; }
        [Required]
        [StringLength(2)]
        [Unicode(false)]
        public string TermCode { get; set; }
        [Required]
        [StringLength(2)]
        [Unicode(false)]
        public string SubtermCode { get; set; }
        [StringLength(96)]
        [Unicode(false)]
        public string Description { get; set; }
        public DateOnly? BeginDate { get; set; }
        public DateOnly? EndDate { get; set; }
    }
}