// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("UserPrivacy_Visibility_Groups", Schema = "dbo")]
public partial class UserPrivacy_Visibility_Groups
{
    public int ID { get; set; }

    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string Group { get; set; }

    [InverseProperty("VisibilityNavigation")]
    public virtual ICollection<UserPrivacy_Settings> UserPrivacy_Settings { get; set; } = new List<UserPrivacy_Settings>();
}