// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.CCT
{
    public partial class VALID_DRIVES_BY_IDResult
    {
        public int? numOccupiedRides { get; set; }
    }
}
