// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.CCT
{
    public partial class VICTORY_PROMISE_BY_STUDENT_IDResult
    {
        public int? TOTAL_VP_IM_SCORE { get; set; }
        public int? TOTAL_VP_CC_SCORE { get; set; }
        public int? TOTAL_VP_LS_SCORE { get; set; }
        public int? TOTAL_VP_LW_SCORE { get; set; }
    }
}
