// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Keyless]
public partial class YearTermTable
{
    public int APPID { get; set; }

    [Required]
    [StringLength(4)]
    [Unicode(false)]
    public string YR_CDE { get; set; }

    [Required]
    [StringLength(2)]
    [Unicode(false)]
    public string TRM_CDE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? TRM_BEGIN_DTE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? TRM_END_DTE { get; set; }

    [StringLength(65)]
    [Unicode(false)]
    public string YR_TRM_DESC { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string PRT_INPROG_ON_TRAN { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CENSUS_DTE { get; set; }

    public int CENSUS_PERCENTAGE { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string SHOW_ON_WEB { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string ONLINE_ADM_APP_OPEN { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string PREREG_STS { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FIRST_DROP_ADD_DTE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LAST_DROP_ADD_DTE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FIRST_FINAL_GRD_DTE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LAST_FINAL_GRD_DTE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FIRST_MIDTRM_GRD_DTE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LAST_MIDTRM_GRD_DTE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LAST_WITHDRAW_PASS_DTE { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string PESC_SESSION_TYPE { get; set; }

    public int? BILLING_PERIOD_ID { get; set; }

    [Column(TypeName = "date")]
    public DateTime? PAYMENT_DUE_DATE { get; set; }

    public bool ONLINE_BALANCE_DISPLAY_DEFAULT { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? STUDENT_WITHDRAWAL_END_DATE { get; set; }

    [Required]
    public byte[] APPROWVERSION { get; set; }

    [StringLength(513)]
    [Unicode(false)]
    public string USER_NAME { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string JOB_NAME { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? JOB_TIME { get; set; }
}