// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.MyGordon
{
    public partial class StudentNewsCategory
    {
        public StudentNewsCategory()
        {
            StudentNews = new HashSet<StudentNews>();
        }

        [Key]
        public int categoryID { get; set; }
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string categoryName { get; set; }
        public int? SortOrder { get; set; }

        [InverseProperty("category")]
        public virtual ICollection<StudentNews> StudentNews { get; set; }
    }
}