// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.StudentTimesheets
{
    public partial class student_timesheets
    {
        [Key]
        public int ID { get; set; }
        /// <summary>
        /// Gordon ID Number
        /// </summary>
        public int ID_NUM { get; set; }
        /// <summary>
        /// a job&apos;s unique id number
        /// </summary>
        public int eml { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string eml_description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime shift_start_datetime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime shift_end_datetime { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal hourly_rate { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal hours_worked { get; set; }
        public int supervisor { get; set; }
        public int comp_supervisor { get; set; }
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string status { get; set; }
        public int? submitted_to { get; set; }
        [Column(TypeName = "text")]
        public string shift_notes { get; set; }
        [Column(TypeName = "text")]
        public string comments { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? pay_week_date { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? pay_period_date { get; set; }
        public int? pay_period_id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string last_changed_by { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime datetime_entered { get; set; }
    }
}