// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.StudentTimesheets
{
    public partial class student_timesheets_select_if_student_has_paid_shiftsResult
    {
        public int ID_NUM { get; set; }
    }
}
