// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.StudentTimesheets
{
    public partial class student_timesheets_select_supervisor_nameResult
    {
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string preferred_name { get; set; }
    }
}
