// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.StudentTimesheets
{
    public partial class student_timesheets_select_fixed_status_shiftsResult
    {
        public string eml_description { get; set; }
        public DateTime shift_start_datetime { get; set; }
        public DateTime shift_end_datetime { get; set; }
        public decimal hours_worked { get; set; }
        public string shift_notes { get; set; }
        public decimal hourly_rate { get; set; }
        public int? submitted_to { get; set; }
        public string status { get; set; }
        public DateTime? pay_week_date { get; set; }
    }
}
