// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.StudentTimesheets
{
    public partial class student_timesheets_edit_shift_already_worked_these_hoursResult
    {
        public int ID { get; set; }
    }
}
