// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Keyless]
    public partial class Birthdays
    {
        public int ID_NUM { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? BIRTH_DTE { get; set; }
    }
}