// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Keyless]
    public partial class Buildings
    {
        [Required]
        [StringLength(5)]
        [Unicode(false)]
        public string BLDG_CDE { get; set; }
        [StringLength(45)]
        [Unicode(false)]
        public string BUILDING_DESC { get; set; }
    }
}