// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.CCT
{
    public partial class CREATE_MESSAGE_ROOMResult
    {
        public bool group { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public DateTime createdAt { get; set; }
        public DateTime lastUpdated { get; set; }
        public byte[] image { get; set; }
    }
}
