// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.CCT
{
    public partial class GET_BIRTH_DATE_BY_IDResult
    {
        public DateTime? Birth_Date { get; set; }
    }
}
