// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.CCT
{
    public partial class GET_TIMESHEETS_CLOCK_IN_OUTResult
    {
        public DateTime? timestamp { get; set; }
        public bool? currentState { get; set; }
    }
}
