// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.CCT
{
    public partial class GET_HEALTH_CHECK_QUESTIONResult
    {
        public string question { get; set; }
        public string yesPrompt { get; set; }
        public string noPrompt { get; set; }
    }
}
