// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.CCT
{
    public partial class GET_AA_APPID_BY_STU_ID_AND_SESSResult
    {
        public int HousingAppID { get; set; }
    }
}
