// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.CCT
{
    public partial class GET_AA_APPLICANTS_DETAILSResult
    {
        public int HousingAppID { get; set; }
        public string EditorUsername { get; set; }
        public DateTime? DateSubmitted { get; set; }
        public DateTime DateModified { get; set; }
        public string Username { get; set; }
        public string AprtProgram { get; set; }
        public bool? AprtProgramCredit { get; set; }
        public string SESS_CDE { get; set; }
    }
}
