// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Index("HousingAppID", Name = "IX_Housing_HallChoices")]
    public partial class Housing_HallChoices
    {
        [Key]
        public long HallChoiceID { get; set; }
        public int HousingAppID { get; set; }
        public int Ranking { get; set; }
        [Required]
        [StringLength(15)]
        [Unicode(false)]
        public string HallName { get; set; }

        [ForeignKey("HousingAppID")]
        [InverseProperty("Housing_HallChoices")]
        public virtual Housing_Applications HousingApp { get; set; }
    }
}