// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Table("League", Schema = "RecIM")]
    public partial class League
    {
        public League()
        {
            Series = new HashSet<Series>();
            Team = new HashSet<Team>();
            UserLeague = new HashSet<UserLeague>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(64)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column(TypeName = "date")]
        public DateTime RegistrationStart { get; set; }
        [Column(TypeName = "date")]
        public DateTime RegistrationEnd { get; set; }
        public int TypeID { get; set; }
        public int SportID { get; set; }
        public int? StatusID { get; set; }
        public int? MinCapacity { get; set; }
        public int? MaxCapacity { get; set; }
        public bool SoloRegistration { get; set; }
        [StringLength(128)]
        [Unicode(false)]
        public string Logo { get; set; }
        public bool Completed { get; set; }

        [ForeignKey("SportID")]
        [InverseProperty("League")]
        public virtual Sport Sport { get; set; }
        [ForeignKey("StatusID")]
        [InverseProperty("League")]
        public virtual LeagueStatus Status { get; set; }
        [ForeignKey("TypeID")]
        [InverseProperty("League")]
        public virtual LeagueType Type { get; set; }
        [InverseProperty("League")]
        public virtual ICollection<Series> Series { get; set; }
        [InverseProperty("League")]
        public virtual ICollection<Team> Team { get; set; }
        [InverseProperty("League")]
        public virtual ICollection<UserLeague> UserLeague { get; set; }
    }
}