// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Table("Match", Schema = "RecIM")]
    public partial class Match
    {
        [Key]
        public int ID { get; set; }
        public int SeriesID { get; set; }
        public int HomeID { get; set; }
        public int? AwayID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Time { get; set; }
        public int SurfaceID { get; set; }
        public int? StatusID { get; set; }
        public int? HomeScore { get; set; }
        public int? AwayScore { get; set; }
        public int? MatchChatID { get; set; }

        [ForeignKey("AwayID")]
        [InverseProperty("MatchAway")]
        public virtual Team Away { get; set; }
        [ForeignKey("HomeID")]
        [InverseProperty("MatchHome")]
        public virtual Team Home { get; set; }
        [ForeignKey("SeriesID")]
        [InverseProperty("Match")]
        public virtual Series Series { get; set; }
        [ForeignKey("StatusID")]
        [InverseProperty("Match")]
        public virtual MatchStatus Status { get; set; }
        [ForeignKey("SurfaceID")]
        [InverseProperty("Match")]
        public virtual Surface Surface { get; set; }
    }
}