// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.CCT
{
    public partial class MYSCHEDULE_BY_IDResult
    {
        public string EVENT_ID { get; set; }
        public string GORDON_ID { get; set; }
        public string LOCATION { get; set; }
        public string DESCRIPTION { get; set; }
        public string MON_CDE { get; set; }
        public string TUE_CDE { get; set; }
        public string WED_CDE { get; set; }
        public string THU_CDE { get; set; }
        public string FRI_CDE { get; set; }
        public string SAT_CDE { get; set; }
        public string SUN_CDE { get; set; }
        public int? IS_ALLDAY { get; set; }
        public TimeSpan? BEGIN_TIME { get; set; }
        public TimeSpan? END_TIME { get; set; }
    }
}
