// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Table("ParticipantTeam", Schema = "RecIM")]
    public partial class ParticipantTeam
    {
        public ParticipantTeam()
        {
            Statistic = new HashSet<Statistic>();
        }

        [Key]
        public int ID { get; set; }
        public int TeamID { get; set; }
        public int ParticipantID { get; set; }
        [Column(TypeName = "date")]
        public DateTime? SignDate { get; set; }
        public int RoleType { get; set; }

        [ForeignKey("ParticipantID")]
        [InverseProperty("ParticipantTeam")]
        public virtual Participant Participant { get; set; }
        [ForeignKey("RoleType")]
        [InverseProperty("ParticipantTeam")]
        public virtual RoleType RoleTypeNavigation { get; set; }
        [ForeignKey("TeamID")]
        [InverseProperty("ParticipantTeam")]
        public virtual Team Team { get; set; }
        [InverseProperty("ParticipantTeam")]
        public virtual ICollection<Statistic> Statistic { get; set; }
    }
}