// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Table("SeriesSurface", Schema = "RecIM")]
    public partial class SeriesSurface
    {
        [Key]
        public int ID { get; set; }
        public int SeriesID { get; set; }
        public int SurfaceID { get; set; }

        [ForeignKey("SeriesID")]
        [InverseProperty("SeriesSurface")]
        public virtual Series Series { get; set; }
        [ForeignKey("SurfaceID")]
        [InverseProperty("SeriesSurface")]
        public virtual Surface Surface { get; set; }
    }
}