// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Table("Sportmanship", Schema = "RecIM")]
    public partial class Sportmanship
    {
        [Key]
        public int ID { get; set; }
        public int TeamID { get; set; }
        public int Rating { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Time { get; set; }

        [ForeignKey("TeamID")]
        [InverseProperty("Sportmanship")]
        public virtual Team Team { get; set; }
    }
}