// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Table("Sport", Schema = "RecIM")]
    public partial class Sport
    {
        public Sport()
        {
            League = new HashSet<League>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(64)]
        [Unicode(false)]
        public string Name { get; set; }
        public bool HasLogo { get; set; }
        [StringLength(128)]
        [Unicode(false)]
        public string Description { get; set; }
        [StringLength(512)]
        [Unicode(false)]
        public string Rules { get; set; }

        [InverseProperty("Sport")]
        public virtual ICollection<League> League { get; set; }
    }
}