// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Table("UserStatusHistory", Schema = "RecIM")]
    public partial class UserStatusHistory
    {
        [Key]
        public int ID { get; set; }
        public int UserID { get; set; }
        public int StatusID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }

        [ForeignKey("StatusID")]
        [InverseProperty("UserStatusHistory")]
        public virtual UserStatus Status { get; set; }
        [ForeignKey("UserID")]
        [InverseProperty("UserStatusHistory")]
        public virtual User User { get; set; }
    }
}