// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gordon360.Models.Gordon360
{
    public partial class FINALIZATION_MARK_AS_CURRENTLY_COMPLETEDResult
    {
        public string UserID { get; set; }
        public string Period { get; set; }
        public bool FinalizationCompleted { get; set; }
        public string RootQuery { get; set; }
        public string BypassApprover { get; set; }
        public DateTime? DateFinalized { get; set; }
        public string IgnoreHoldsApprover { get; set; }
        public DateTime DateInserted { get; set; }
        public DateTime DateUpdated { get; set; }
        public string HeadcountsAsOfDateFinalized { get; set; }
    }
}
