// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.Gordon360;

[Keyless]
public partial class Mailboxes
{
    public int BoxId { get; set; }

    [Required]
    [StringLength(32)]
    [Unicode(false)]
    public string BoxNo { get; set; }

    [StringLength(16)]
    [Unicode(false)]
    public string Combination { get; set; }

    [Required]
    [StringLength(32)]
    [Unicode(false)]
    public string Type { get; set; }

    public int? HolderAccountId { get; set; }
}