// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.Gordon360;

[Keyless]
public partial class States
{
    [Required]
    [StringLength(63)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(31)]
    [Unicode(false)]
    public string Abbreviation { get; set; }
}