// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Gordon360.Models.CCT;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT.Context;

public partial class CCTContext : DbContext
{
    public CCTContext(DbContextOptions<CCTContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ACCOUNT> ACCOUNT { get; set; }

    public virtual DbSet<AccountPhotoURL> AccountPhotoURL { get; set; }

    public virtual DbSet<Activity> Activity { get; set; }

    public virtual DbSet<ActivityStatus> ActivityStatus { get; set; }

    public virtual DbSet<ActivityType> ActivityType { get; set; }

    public virtual DbSet<Affiliation> Affiliation { get; set; }

    public virtual DbSet<AffiliationPoints> AffiliationPoints { get; set; }

    public virtual DbSet<Alumni> Alumni { get; set; }

    public virtual DbSet<CM_SESSION_MSTR> CM_SESSION_MSTR { get; set; }

    public virtual DbSet<ChapelEvent> ChapelEvent { get; set; }

    public virtual DbSet<Countries> Countries { get; set; }

    public virtual DbSet<CustomParticipant> CustomParticipant { get; set; }

    public virtual DbSet<DiningInfo> DiningInfo { get; set; }

    public virtual DbSet<EmergencyContact> EmergencyContact { get; set; }

    public virtual DbSet<FacStaff> FacStaff { get; set; }

    public virtual DbSet<Hall_Assignment_Ranges> Hall_Assignment_Ranges { get; set; }

    public virtual DbSet<Halls> Halls { get; set; }

    public virtual DbSet<InvolvementOffering> InvolvementOffering { get; set; }

    public virtual DbSet<Mailboxes> Mailboxes { get; set; }

    public virtual DbSet<Majors> Majors { get; set; }

    public virtual DbSet<Match> Match { get; set; }

    public virtual DbSet<MatchBracket> MatchBracket { get; set; }

    public virtual DbSet<MatchParticipant> MatchParticipant { get; set; }

    public virtual DbSet<MatchStatus> MatchStatus { get; set; }

    public virtual DbSet<MatchTeam> MatchTeam { get; set; }

    public virtual DbSet<MatchTeamStatus> MatchTeamStatus { get; set; }

    public virtual DbSet<MembershipView> MembershipView { get; set; }

    public virtual DbSet<Minors> Minors { get; set; }

    public virtual DbSet<PART_DEF> PART_DEF { get; set; }

    public virtual DbSet<Participant> Participant { get; set; }

    public virtual DbSet<ParticipantActivity> ParticipantActivity { get; set; }

    public virtual DbSet<ParticipantNotification> ParticipantNotification { get; set; }

    public virtual DbSet<ParticipantStatus> ParticipantStatus { get; set; }

    public virtual DbSet<ParticipantStatusHistory> ParticipantStatusHistory { get; set; }

    public virtual DbSet<ParticipantTeam> ParticipantTeam { get; set; }

    public virtual DbSet<ParticipantView> ParticipantView { get; set; }

    public virtual DbSet<PrivType> PrivType { get; set; }

    public virtual DbSet<RA_On_Call> RA_On_Call { get; set; }

    public virtual DbSet<RA_On_Call_History> RA_On_Call_History { get; set; }

    public virtual DbSet<RA_Status> RA_Status { get; set; }

    public virtual DbSet<RA_Status_History> RA_Status_History { get; set; }

    public virtual DbSet<RA_Status_Schedule> RA_Status_Schedule { get; set; }

    public virtual DbSet<RA_Task_Status> RA_Task_Status { get; set; }

    public virtual DbSet<RA_Tasks> RA_Tasks { get; set; }

    public virtual DbSet<Recurrence> Recurrence { get; set; }

    public virtual DbSet<RequestView> RequestView { get; set; }

    public virtual DbSet<Resident_Advisor> Resident_Advisor { get; set; }

    public virtual DbSet<RoleType> RoleType { get; set; }

    public virtual DbSet<Series> Series { get; set; }

    public virtual DbSet<SeriesSchedule> SeriesSchedule { get; set; }

    public virtual DbSet<SeriesStatus> SeriesStatus { get; set; }

    public virtual DbSet<SeriesSurface> SeriesSurface { get; set; }

    public virtual DbSet<SeriesTeam> SeriesTeam { get; set; }

    public virtual DbSet<SeriesTeamView> SeriesTeamView { get; set; }

    public virtual DbSet<SeriesType> SeriesType { get; set; }

    public virtual DbSet<Sport> Sport { get; set; }

    public virtual DbSet<States> States { get; set; }

    public virtual DbSet<Statistic> Statistic { get; set; }

    public virtual DbSet<Student> Student { get; set; }

    public virtual DbSet<Surface> Surface { get; set; }

    public virtual DbSet<Team> Team { get; set; }

    public virtual DbSet<TeamStatus> TeamStatus { get; set; }

    public virtual DbSet<UserCourses> UserCourses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ACCOUNT>(entity =>
        {
            entity.ToView("ACCOUNT", "dbo");
        });

        modelBuilder.Entity<AccountPhotoURL>(entity =>
        {
            entity.ToView("AccountPhotoURL", "dbo");
        });

        modelBuilder.Entity<Activity>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Activity__3214EC2752162A10");

            entity.HasOne(d => d.SeriesSchedule).WithMany(p => p.Activity).HasConstraintName("FK_Activity_SeriesSchedule");

            entity.HasOne(d => d.Sport).WithMany(p => p.Activity)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Activity_Sport");

            entity.HasOne(d => d.Status).WithMany(p => p.Activity)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Activity_ActivityStatus");

            entity.HasOne(d => d.Type).WithMany(p => p.Activity)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Activity_ActivityType");
        });

        modelBuilder.Entity<Affiliation>(entity =>
        {
            entity.HasKey(e => e.Name).HasName("PK_Affiliations");
        });

        modelBuilder.Entity<AffiliationPoints>(entity =>
        {
            entity.HasOne(d => d.AffiliationNameNavigation).WithMany(p => p.AffiliationPoints)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AffiliationPoints_Affiliations");

            entity.HasOne(d => d.Series).WithMany(p => p.AffiliationPoints)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AffiliationPoints_Series");

            entity.HasOne(d => d.Team).WithMany(p => p.AffiliationPoints)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AffiliationPoints_Team");
        });

        modelBuilder.Entity<Alumni>(entity =>
        {
            entity.ToView("Alumni", "dbo");

            entity.Property(e => e.grad_student).IsFixedLength();
        });

        modelBuilder.Entity<CM_SESSION_MSTR>(entity =>
        {
            entity.ToView("CM_SESSION_MSTR", "dbo");

            entity.Property(e => e.SESS_CDE).IsFixedLength();
        });

        modelBuilder.Entity<ChapelEvent>(entity =>
        {
            entity.ToView("ChapelEvent", "dbo");
        });

        modelBuilder.Entity<Countries>(entity =>
        {
            entity.ToView("Countries", "dbo");

            entity.Property(e => e.CTY).IsFixedLength();
        });

        modelBuilder.Entity<CustomParticipant>(entity =>
        {
            entity.HasKey(e => e.Username).HasName("PK__CustomPa__536C85E5A0FDE2AE");

            entity.Property(e => e.ID).ValueGeneratedOnAdd();

            entity.HasOne(d => d.UsernameNavigation).WithOne(p => p.CustomParticipant)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CustomPar__Usern__70D3A237");
        });

        modelBuilder.Entity<DiningInfo>(entity =>
        {
            entity.ToView("DiningInfo", "dbo");

            entity.Property(e => e.ChoiceDescription).IsFixedLength();
            entity.Property(e => e.SessionCode).IsFixedLength();
        });

        modelBuilder.Entity<EmergencyContact>(entity =>
        {
            entity.ToView("EmergencyContact", "dbo");

            entity.Property(e => e.AddressAddrCode).IsFixedLength();
            entity.Property(e => e.ApprowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.EmailAddrCode).IsFixedLength();
            entity.Property(e => e.HomeAddrCode).IsFixedLength();
            entity.Property(e => e.HomeExt).IsFixedLength();
            entity.Property(e => e.HomePhone).IsFixedLength();
            entity.Property(e => e.MobileAddrCode).IsFixedLength();
            entity.Property(e => e.MobileExt).IsFixedLength();
            entity.Property(e => e.MobilePhone).IsFixedLength();
            entity.Property(e => e.WorkAddrCode).IsFixedLength();
            entity.Property(e => e.WorkExr).IsFixedLength();
            entity.Property(e => e.WorkPhone).IsFixedLength();
        });

        modelBuilder.Entity<FacStaff>(entity =>
        {
            entity.ToView("FacStaff", "dbo");

            entity.Property(e => e.BuildingDescription).IsFixedLength();
        });

        modelBuilder.Entity<Hall_Assignment_Ranges>(entity =>
        {
            entity.HasKey(e => e.Range_ID).HasName("PK__Hall_Ass__918829E78BFD242E");

            entity.HasOne(d => d.Hall).WithMany(p => p.Hall_Assignment_Ranges).HasConstraintName("FK__Hall_Assi__Hall___1FE396DB");

            entity.HasMany(d => d.Ra).WithMany(p => p.Range)
                .UsingEntity<Dictionary<string, object>>(
                    "RA_Assigned_Ranges",
                    r => r.HasOne<Resident_Advisor>().WithMany()
                        .HasForeignKey("Ra_ID")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__RA_Assign__Ra_ID__23B427BF"),
                    l => l.HasOne<Hall_Assignment_Ranges>().WithMany()
                        .HasForeignKey("Range_ID")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__RA_Assign__Range__22C00386"),
                    j =>
                    {
                        j.HasKey("Range_ID", "Ra_ID").HasName("PK__RA_Assig__48DB2FD1B0A5147D");
                        j.ToTable("RA_Assigned_Ranges", "Housing");
                    });
        });

        modelBuilder.Entity<Halls>(entity =>
        {
            entity.HasMany(d => d.Accessible_Hall).WithMany(p => p.Hall)
                .UsingEntity<Dictionary<string, object>>(
                    "Hall_Permissions",
                    r => r.HasOne<Halls>().WithMany()
                        .HasForeignKey("Accessible_Hall_ID")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__Hall_Perm__Acces__15660868"),
                    l => l.HasOne<Halls>().WithMany()
                        .HasForeignKey("Hall_ID")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__Hall_Perm__Hall___1471E42F"),
                    j =>
                    {
                        j.HasKey("Hall_ID", "Accessible_Hall_ID").HasName("PK__Hall_Per__BEF631825AADE55A");
                        j.ToTable("Hall_Permissions", "Housing");
                    });

            entity.HasMany(d => d.Hall).WithMany(p => p.Accessible_Hall)
                .UsingEntity<Dictionary<string, object>>(
                    "Hall_Permissions",
                    r => r.HasOne<Halls>().WithMany()
                        .HasForeignKey("Hall_ID")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__Hall_Perm__Hall___1471E42F"),
                    l => l.HasOne<Halls>().WithMany()
                        .HasForeignKey("Accessible_Hall_ID")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__Hall_Perm__Acces__15660868"),
                    j =>
                    {
                        j.HasKey("Hall_ID", "Accessible_Hall_ID").HasName("PK__Hall_Per__BEF631825AADE55A");
                        j.ToTable("Hall_Permissions", "Housing");
                    });
        });

        modelBuilder.Entity<InvolvementOffering>(entity =>
        {
            entity.ToView("InvolvementOffering", "dbo");

            entity.Property(e => e.ActivityCode).IsFixedLength();
            entity.Property(e => e.ActivityDescription).IsFixedLength();
            entity.Property(e => e.ActivityType).IsFixedLength();
            entity.Property(e => e.ActivityTypeDescription).IsFixedLength();
            entity.Property(e => e.SessionCode).IsFixedLength();
        });

        modelBuilder.Entity<Mailboxes>(entity =>
        {
            entity.ToView("Mailboxes", "dbo");
        });

        modelBuilder.Entity<Majors>(entity =>
        {
            entity.ToView("Majors", "dbo");
        });

        modelBuilder.Entity<Match>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Match__3214EC27BB2F05C8");

            entity.Property(e => e.SurfaceID).HasDefaultValue(1);

            entity.HasOne(d => d.Series).WithMany(p => p.Match).HasConstraintName("FK_Match_Series");

            entity.HasOne(d => d.Status).WithMany(p => p.Match)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Match_MatchStatus");

            entity.HasOne(d => d.Surface).WithMany(p => p.Match)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Match_Surface");
        });

        modelBuilder.Entity<MatchBracket>(entity =>
        {
            entity.Property(e => e.MatchID).ValueGeneratedNever();

            entity.HasOne(d => d.Match).WithOne(p => p.MatchBracket)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MatchBracket_Match");
        });

        modelBuilder.Entity<MatchParticipant>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__MatchPar__3214EC27DFD38F69");

            entity.HasOne(d => d.Match).WithMany(p => p.MatchParticipant)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MatchParticipant_Match");

            entity.HasOne(d => d.ParticipantUsernameNavigation).WithMany(p => p.MatchParticipant)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MatchParticipant_Participant");

            entity.HasOne(d => d.Team).WithMany(p => p.MatchParticipant)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MatchParticipant_Team");
        });

        modelBuilder.Entity<MatchTeam>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__MatchTea__3214EC2743BD85C3");

            entity.HasOne(d => d.Match).WithMany(p => p.MatchTeam).HasConstraintName("FK_MatchTeam_Match");

            entity.HasOne(d => d.Status).WithMany(p => p.MatchTeam)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MatchTeam_MatchTeamStatus");

            entity.HasOne(d => d.Team).WithMany(p => p.MatchTeam).HasConstraintName("FK_MatchTeam_Team");
        });

        modelBuilder.Entity<MembershipView>(entity =>
        {
            entity.ToView("MembershipView", "dbo");

            entity.Property(e => e.ActivityDescription).IsFixedLength();
        });

        modelBuilder.Entity<Minors>(entity =>
        {
            entity.ToView("Minors", "dbo");
        });

        modelBuilder.Entity<PART_DEF>(entity =>
        {
            entity.ToView("PART_DEF", "dbo");

            entity.Property(e => e.PART_CDE).IsFixedLength();
            entity.Property(e => e.PART_DESC).IsFixedLength();
        });

        modelBuilder.Entity<Participant>(entity =>
        {
            entity.Property(e => e.AllowEmails).HasDefaultValue(true);
            entity.Property(e => e.ID).ValueGeneratedOnAdd();
            entity.Property(e => e.SpecifiedGender).IsFixedLength();
        });

        modelBuilder.Entity<ParticipantActivity>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Particip__3214EC27C3ECBD4A");

            entity.HasOne(d => d.Activity).WithMany(p => p.ParticipantActivity).HasConstraintName("FK_ParticipantActivity_Activity");

            entity.HasOne(d => d.ParticipantUsernameNavigation).WithMany(p => p.ParticipantActivity)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ParticipantActivity_Participant");

            entity.HasOne(d => d.PrivType).WithMany(p => p.ParticipantActivity)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PrivType_ParticipantActivity");
        });

        modelBuilder.Entity<ParticipantNotification>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Particip__3214EC2702C79C04");

            entity.HasOne(d => d.ParticipantUsernameNavigation).WithMany(p => p.ParticipantNotification)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ParticipantNotification_Participant");
        });

        modelBuilder.Entity<ParticipantStatusHistory>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Particip__3214EC2705A45A77");

            entity.HasOne(d => d.ParticipantUsernameNavigation).WithMany(p => p.ParticipantStatusHistory)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ParticipantStatusHistory_Participant");

            entity.HasOne(d => d.Status).WithMany(p => p.ParticipantStatusHistory)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ParticipantStatusHistory_ParticipantStatus");
        });

        modelBuilder.Entity<ParticipantTeam>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Particip__3214EC27CA13A740");

            entity.HasOne(d => d.ParticipantUsernameNavigation).WithMany(p => p.ParticipantTeam)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ParticipantTeam_Participant");

            entity.HasOne(d => d.RoleType).WithMany(p => p.ParticipantTeam)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoleType_ParticipantTeam");

            entity.HasOne(d => d.Team).WithMany(p => p.ParticipantTeam).HasConstraintName("FK_ParticipantTeam_Team");
        });

        modelBuilder.Entity<ParticipantView>(entity =>
        {
            entity.ToView("ParticipantView", "RecIM");

            entity.Property(e => e.Hall).IsFixedLength();
            entity.Property(e => e.SpecifiedGender).IsFixedLength();
        });

        modelBuilder.Entity<RA_On_Call>(entity =>
        {
            entity.HasKey(e => new { e.Hall_ID, e.Ra_ID }).HasName("PK__RA_On_Ca__4B2C77107B706BE7");

            entity.HasOne(d => d.Hall).WithMany(p => p.RA_On_Call)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RA_On_Cal__Hall___18427513");

            entity.HasOne(d => d.Ra).WithMany(p => p.RA_On_Call)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RA_On_Cal__Ra_ID__1936994C");
        });

        modelBuilder.Entity<RA_On_Call_History>(entity =>
        {
            entity.HasKey(e => e.Record_ID).HasName("PK__RA_On_Ca__603A0C6045336E5A");

            entity.HasOne(d => d.Hall).WithMany(p => p.RA_On_Call_History).HasConstraintName("FK__RA_On_Cal__Hall___1C1305F7");

            entity.HasOne(d => d.Ra).WithMany(p => p.RA_On_Call_History).HasConstraintName("FK__RA_On_Cal__Ra_ID__1D072A30");
        });

        modelBuilder.Entity<RA_Status>(entity =>
        {
            entity.HasKey(e => new { e.Ra_ID, e.Status_name }).HasName("PK__RA_Statu__D0CCD16385537CA7");

            entity.HasOne(d => d.Ra).WithMany(p => p.RA_Status)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RA_Status__Ra_ID__0717E911");
        });

        modelBuilder.Entity<RA_Status_History>(entity =>
        {
            entity.HasKey(e => e.Record_ID).HasName("PK__RA_Statu__603A0C6074EFB375");

            entity.HasOne(d => d.Ra).WithMany(p => p.RA_Status_History).HasConstraintName("FK__RA_Status__Ra_ID__11957784");
        });

        modelBuilder.Entity<RA_Status_Schedule>(entity =>
        {
            entity.HasKey(e => e.Sched_ID).HasName("PK__RA_Statu__67FBEF061E83AAC9");

            entity.HasOne(d => d.Ra).WithMany(p => p.RA_Status_Schedule).HasConstraintName("FK__RA_Status__Ra_ID__0DC4E6A0");

            entity.HasOne(d => d.recur).WithMany(p => p.RA_Status_Schedule).HasConstraintName("FK__RA_Status__recur__0EB90AD9");
        });

        modelBuilder.Entity<RA_Task_Status>(entity =>
        {
            entity.HasKey(e => new { e.Ra_ID, e.Task_ID }).HasName("PK__RA_Task___522697C0F2F5407E");

            entity.HasOne(d => d.Ra).WithMany(p => p.RA_Task_Status)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RA_Task_S__Ra_ID__2878DCDC");

            entity.HasOne(d => d.Task).WithMany(p => p.RA_Task_Status)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RA_Task_S__Task___296D0115");
        });

        modelBuilder.Entity<RA_Tasks>(entity =>
        {
            entity.HasKey(e => e.Task_ID).HasName("PK__RA_Tasks__716F4ACD264F4856");
        });

        modelBuilder.Entity<Recurrence>(entity =>
        {
            entity.HasKey(e => e.recur_ID).HasName("PK__Recurren__69860EC35971086A");
        });

        modelBuilder.Entity<RequestView>(entity =>
        {
            entity.ToView("RequestView", "dbo");

            entity.Property(e => e.ActivityDescription).IsFixedLength();
            entity.Property(e => e.ParticipationDescription).IsFixedLength();
        });

        modelBuilder.Entity<Resident_Advisor>(entity =>
        {
            entity.HasKey(e => e.Ra_ID).HasName("PK__Resident__9530636CD75B0459");

            entity.HasOne(d => d.Hall).WithMany(p => p.Resident_Advisor).HasConstraintName("FK__Resident___Hall___043B7C66");
        });

        modelBuilder.Entity<Series>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Series__3214EC27544E6A66");

            entity.HasOne(d => d.Activity).WithMany(p => p.Series)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Series_Activity");

            entity.HasOne(d => d.Schedule).WithMany(p => p.Series)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SeriesSchedule_Series");

            entity.HasOne(d => d.Status).WithMany(p => p.Series)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SeriesStatus_Series");

            entity.HasOne(d => d.Type).WithMany(p => p.Series)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Series_SeriesType");

            entity.HasOne(d => d.Winner).WithMany(p => p.Series).HasConstraintName("FK_Series_Team");
        });

        modelBuilder.Entity<SeriesSurface>(entity =>
        {
            entity.HasOne(d => d.Series).WithMany(p => p.SeriesSurface).HasConstraintName("FK_SeriesSurface_Series");

            entity.HasOne(d => d.Surface).WithMany(p => p.SeriesSurface).HasConstraintName("FK_SeriesSurface_Surface");
        });

        modelBuilder.Entity<SeriesTeam>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__SeriesTe__3214EC27F3AD6274");

            entity.HasOne(d => d.Series).WithMany(p => p.SeriesTeam).HasConstraintName("FK_SeriesTeam_Series");

            entity.HasOne(d => d.Team).WithMany(p => p.SeriesTeam).HasConstraintName("FK_SeriesTeam_Team");
        });

        modelBuilder.Entity<SeriesTeamView>(entity =>
        {
            entity.ToView("SeriesTeamView", "RecIM");
        });

        modelBuilder.Entity<SeriesType>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__SeriesTy__3214EC270DA32B2F");
        });

        modelBuilder.Entity<Sport>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Sport__3214EC276FB2D545");
        });

        modelBuilder.Entity<States>(entity =>
        {
            entity.ToView("States", "dbo");
        });

        modelBuilder.Entity<Statistic>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Statisti__3214EC2707DA8F6B");

            entity.HasOne(d => d.ParticipantTeam).WithMany(p => p.Statistic)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Statistic_ParticipantTeam");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.ToView("Student", "dbo");

            entity.Property(e => e.BuildingDescription).IsFixedLength();
        });

        modelBuilder.Entity<Surface>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Surface__3214EC27629CF90A");
        });

        modelBuilder.Entity<Team>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Team__3214EC27A55EA0D3");

            entity.HasOne(d => d.Activity).WithMany(p => p.Team).HasConstraintName("FK_Team_Activity");

            entity.HasOne(d => d.AffiliationNavigation).WithMany(p => p.Team)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Team_Affiliations");

            entity.HasOne(d => d.Status).WithMany(p => p.Team)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Team_TeamStatus");
        });

        modelBuilder.Entity<UserCourses>(entity =>
        {
            entity.ToView("UserCourses", "dbo");

            entity.Property(e => e.BLDG_CDE).IsFixedLength();
            entity.Property(e => e.CRS_CDE).IsFixedLength();
            entity.Property(e => e.CRS_TITLE).IsFixedLength();
            entity.Property(e => e.FRIDAY_CDE).IsFixedLength();
            entity.Property(e => e.MONDAY_CDE).IsFixedLength();
            entity.Property(e => e.ROOM_CDE).IsFixedLength();
            entity.Property(e => e.SATURDAY_CDE).IsFixedLength();
            entity.Property(e => e.SUBTERM_DESC).IsFixedLength();
            entity.Property(e => e.SUNDAY_CDE).IsFixedLength();
            entity.Property(e => e.THURSDAY_CDE).IsFixedLength();
            entity.Property(e => e.TRM_CDE).IsFixedLength();
            entity.Property(e => e.TUESDAY_CDE).IsFixedLength();
            entity.Property(e => e.WEDNESDAY_CDE).IsFixedLength();
            entity.Property(e => e.YR_CDE).IsFixedLength();
        });
        modelBuilder.HasSequence("Information_Change_Request_Seq", "dbo");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}