// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[PrimaryKey("ApplicationID", "Applicant1")]
[Table("Applicant", Schema = "Housing")]
public partial class Applicant
{
    [Key]
    [StringLength(255)]
    [Unicode(false)]
    public string ApplicationID { get; set; }

    [Key]
    [Column("Applicant")]
    [StringLength(255)]
    [Unicode(false)]
    public string Applicant1 { get; set; }
}