// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Keyless]
public partial class CurrentStatusEvents
{
    public int Status_ID { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Ra_ID { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Status_Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Occur_Date { get; set; }

    public bool Is_Complete { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Completed_Date { get; set; }
}