// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Keyless]
public partial class Daily_RA_Events
{
    public int Status_ID { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Ra_ID { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Status_Name { get; set; }

    public bool Is_Recurring { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Frequency { get; set; }

    public int? Interval { get; set; }

    [Column(TypeName = "date")]
    public DateTime Start_Date { get; set; }

    [Column(TypeName = "date")]
    public DateTime? End_Date { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created_Date { get; set; }

    public TimeSpan? Start_Time { get; set; }

    public TimeSpan? End_Time { get; set; }

    public bool Available { get; set; }
  
}