// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("DueDate", Schema = "Housing")]
public partial class DueDate
{
    [Key]
    [Column("DueDate")]
    [StringLength(255)]
    [Unicode(false)]
    public string DueDate1 { get; set; }
}