// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("Hall_Task_Recurrence", Schema = "Housing")]
public partial class Hall_Task_Recurrence
{
    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Recur_ID { get; set; }

    [Key]
    public int Task_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Next_Occurance { get; set; }
}