// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("Hall_Assignment_Ranges", Schema = "Housing")]
public partial class Hall_Assignment_Ranges
{
    [Key]
    public int Range_ID { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Hall_ID { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Room_Start { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Room_End { get; set; }

    [InverseProperty("Range")]
    public virtual ICollection<RA_Assigned_Ranges> RA_Assigned_Ranges { get; set; } = new List<RA_Assigned_Ranges>();
}