// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("Halls", Schema = "Housing")]
public partial class Halls
{
    [Key]
    public int Hall_ID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [InverseProperty("Hall")]
    public virtual ICollection<Hall_Assignment_Ranges> Hall_Assignment_Ranges { get; set; } = new List<Hall_Assignment_Ranges>();

    [InverseProperty("Hall")]
    public virtual ICollection<RA_On_Call> RA_On_Call { get; set; } = new List<RA_On_Call>();

    [InverseProperty("Hall")]
    public virtual ICollection<Resident_Advisor> Resident_Advisor { get; set; } = new List<Resident_Advisor>();

    [ForeignKey("Hall_ID")]
    [InverseProperty("Hall")]
    public virtual ICollection<Halls> Accessible_Hall { get; set; } = new List<Halls>();

    [ForeignKey("Accessible_Hall_ID")]
    [InverseProperty("Accessible_Hall")]
    public virtual ICollection<Halls> Hall { get; set; } = new List<Halls>();
}