// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("Hall_Tasks", Schema = "Housing")]
public partial class Hall_Tasks
{
    [Key]
    public int Task_ID { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Task_Name { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Hall_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Task_Date { get; set; }

    public bool Is_Recurring { get; set; }

    public bool Is_Completed { get; set; }
}