// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[PrimaryKey("ApplicationID", "Rank")]
[Table("PreferredHall", Schema = "Housing")]
public partial class PreferredHall
{
    [Key]
    [StringLength(255)]
    [Unicode(false)]
    public string ApplicationID { get; set; }

    [Key]
    public int Rank { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string HallName { get; set; }
}