// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[PrimaryKey("Range_ID", "Ra_ID")]
[Table("RA_Assigned_Ranges", Schema = "Housing")]
public partial class RA_Assigned_Ranges
{
    [Key]
    public int Range_ID { get; set; }

    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string Ra_ID { get; set; }

    [ForeignKey("Range_ID")]
    [InverseProperty("RA_Assigned_Ranges")]
    public virtual Hall_Assignment_Ranges Range { get; set; }
}