// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[PrimaryKey("Ra_ID", "Status_name")]
[Table("RA_Status", Schema = "Housing")]
public partial class RA_Status
{
    [Key]
    public int Ra_ID { get; set; }

    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string Status_name { get; set; }

    [ForeignKey("Ra_ID")]
    [InverseProperty("RA_Status")]
    public virtual Resident_Advisor Ra { get; set; }
}