// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("RA_Status_Event_Occurrence", Schema = "Housing")]
public partial class RA_Status_Event_Occurrence
{
    [Key]
    public int Occur_ID { get; set; }

    public int Status_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Occur_Date { get; set; }

    public bool Is_Complete { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Completed_Date { get; set; }
}