// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[PrimaryKey("Ra_ID", "Task_ID")]
[Table("RA_Task_Status", Schema = "Housing")]
public partial class RA_Task_Status
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string Ra_ID { get; set; }

    [Key]
    public int Task_ID { get; set; }

    public bool? Is_Completed { get; set; }

    [ForeignKey("Task_ID")]
    [InverseProperty("RA_Task_Status")]
    public virtual RA_Tasks Task { get; set; }
}