// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("RA_Tasks", Schema = "Housing")]
public partial class RA_Tasks
{
    [Key]
    public int Task_ID { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Task_Name { get; set; }

    [InverseProperty("Task")]
    public virtual ICollection<RA_Task_Status> RA_Task_Status { get; set; } = new List<RA_Task_Status>();
}