// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Keyless]
public partial class RD_OnCall_Today
{
    [Column("RD Email")]
    [StringLength(50)]
    [Unicode(false)]
    public string RD_Email { get; set; }

    [StringLength(10)]
    public string RDId { get; set; }

    [Required]
    [StringLength(46)]
    [Unicode(false)]
    public string RDName { get; set; }

    [Column(TypeName = "date")]
    public DateTime Start_Date { get; set; }

    [Column(TypeName = "date")]
    public DateTime End_Date { get; set; }
}