// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("Recurrence", Schema = "Housing")]
public partial class Recurrence
{
    [Key]
    public int recur_ID { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string frequency { get; set; }

    public int? Recurrence_interval { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string day_of_week { get; set; }

    [Column(TypeName = "date")]
    public DateTime? end_date { get; set; }

    [InverseProperty("recur")]
    public virtual ICollection<RA_Status_Schedule> RA_Status_Schedule { get; set; } = new List<RA_Status_Schedule>();
}