// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Keyless]
public partial class ResidentialStatus_View
{
    public int Student_ID { get; set; }

    [Required]
    [StringLength(8)]
    [Unicode(false)]
    public string Latest_Session { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Residency_Status { get; set; }

    public int Is_Residential { get; set; }
}