// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("Resident_Advisor", Schema = "Housing")]
public partial class Resident_Advisor
{
    [Key]
    public int Ra_ID { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Fname { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Lname { get; set; }

    public int? Hall_ID { get; set; }

    public int? Floor { get; set; }

    public int? Room_Num { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Pref_contact { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Term_code { get; set; }

    [ForeignKey("Hall_ID")]
    [InverseProperty("Resident_Advisor")]
    public virtual Halls Hall { get; set; }

    [InverseProperty("Ra")]
    public virtual ICollection<RA_On_Call> RA_On_Call { get; set; } = new List<RA_On_Call>();

    [InverseProperty("Ra")]
    public virtual ICollection<RA_On_Call_History> RA_On_Call_History { get; set; } = new List<RA_On_Call_History>();

    [InverseProperty("Ra")]
    public virtual ICollection<RA_Status> RA_Status { get; set; } = new List<RA_Status>();

    [InverseProperty("Ra")]
    public virtual ICollection<RA_Status_History> RA_Status_History { get; set; } = new List<RA_Status_History>();

    [InverseProperty("Ra")]
    public virtual ICollection<RA_Status_Schedule> RA_Status_Schedule { get; set; } = new List<RA_Status_Schedule>();

    [InverseProperty("Ra")]
    public virtual ICollection<RA_Task_Status> RA_Task_Status { get; set; } = new List<RA_Task_Status>();

    [ForeignKey("Ra_ID")]
    [InverseProperty("Ra")]
    public virtual ICollection<Hall_Assignment_Ranges> Range { get; set; } = new List<Hall_Assignment_Ranges>();
}