// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Keyless]
[Table("ResRooms", Schema = "Housing")]
public partial class ResRooms
{
    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Room_Name { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Building_Code { get; set; }

    public int Floor_Number { get; set; }

    public int Room_Number { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string RA_Type { get; set; }
}