// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT
{
    [Table("Roommate", Schema = "Housing")]
    public partial class Roommate
    {
        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(128)]
        [Unicode(false)]
        public string Name { get; set; }
        [Key]
        [StringLength(128)]
        [Unicode(false)]
        public string RoommateName { get; set; }
    }
}