// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("StuLifePhoneNumbers", Schema = "Housing")]
public partial class StuLifePhoneNumbers
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(100)]
    public string PhoneName { get; set; }

    [Required]
    [StringLength(20)]
    public string PhoneNumber { get; set; }

    [StringLength(255)]
    public string Description { get; set; }
}