// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[PrimaryKey("ApplicationID", "Year1")]
[Table("Year", Schema = "Housing")]
public partial class Year
{
    [Key]
    public string ApplicationID { get; set; }

    [Key]
    [Column("Year")]
    [StringLength(255)]
    [Unicode(false)]
    public string Year1 { get; set; }
}