// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("ItemCondition", Schema = "Marketplace")]
public partial class ItemCondition
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string ConditionName { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Visible { get; set; }

    [InverseProperty("Condition")]
    public virtual ICollection<PostedItem> PostedItem { get; set; } = new List<PostedItem>();
}