// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("PostedItem", Schema = "Marketplace")]
public partial class PostedItem
{
    [Key]
    public int Id { get; set; }

    public int PostedById { get; set; }

    public DateTime PostedAt { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Column(TypeName = "money")]
    public decimal Price { get; set; }

    public int CategoryId { get; set; }

    [Required]
    [StringLength(1000)]
    public string Detail { get; set; }

    public int ConditionId { get; set; }

    public int StatusId { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("PostedItem")]
    public virtual ItemCategory Category { get; set; }

    [ForeignKey("ConditionId")]
    [InverseProperty("PostedItem")]
    public virtual ItemCondition Condition { get; set; }

    [InverseProperty("PostedItem")]
    public virtual ICollection<PostImage> PostImage { get; set; } = new List<PostImage>();

    [ForeignKey("StatusId")]
    [InverseProperty("PostedItem")]
    public virtual ItemStatus Status { get; set; }
}