// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("PostImage", Schema = "Marketplace")]
public partial class PostImage
{
    [Key]
    public int Id { get; set; }

    public int PostedItemId { get; set; }

    [Required]
    [StringLength(511)]
    [Unicode(false)]
    public string ImagePath { get; set; }

    [ForeignKey("PostedItemId")]
    [InverseProperty("PostImage")]
    public virtual PostedItem PostedItem { get; set; }
}