// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Keyless]
public partial class Post
{
    public int Id { get; set; }

    public int CategoryId { get; set; }

    [Required]
    [StringLength(50)]
    public string CategoryName { get; set; }

    public int ConditionId { get; set; }

    [Required]
    [StringLength(50)]
    public string ConditionName { get; set; }

    public DateTime? DeletedAt { get; set; }

    [Required]
    [StringLength(1000)]
    public string Detail { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public int? OriginalPostId { get; set; }

    public DateTime PostedAt { get; set; }

    public int PostedById { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PostedByUsername { get; set; }

    [Column(TypeName = "money")]
    public decimal Price { get; set; }

    public int StatusId { get; set; }

    [Required]
    [StringLength(50)]
    public string StatusName { get; set; }

    [StringLength(8000)]
    [Unicode(false)]
    public string ImagePaths { get; set; }
}