//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordon360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_ApartmentApplications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AA_ApartmentApplications()
        {
            this.AA_ApartmentChoices = new HashSet<AA_ApartmentChoices>();
            this.AA_Applicants = new HashSet<AA_Applicants>();
        }
    
        public int AprtAppID { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public System.DateTime DateModified { get; set; }
        public string EditorUsername { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AA_ApartmentChoices> AA_ApartmentChoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AA_Applicants> AA_Applicants { get; set; }
    }
}
