
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gordon360.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ACT_INFO
{

    public string ACT_CDE { get; set; }

    public string ACT_DESC { get; set; }

    public string ACT_BLURB { get; set; }

    public string ACT_URL { get; set; }

    public string ACT_IMG_PATH { get; set; }

    public string ACT_TYPE { get; set; }

    public string ACT_TYPE_DESC { get; set; }

    public Nullable<bool> PRIVACY { get; set; }

    public string ACT_JOIN_INFO { get; set; }

}

}
