
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gordon360.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Alumni
{

    public string ID { get; set; }

    public string WebUpdate { get; set; }

    public string Title { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string Suffix { get; set; }

    public string MaidenName { get; set; }

    public string NickName { get; set; }

    public string HomeStreet1 { get; set; }

    public string HomeStreet2 { get; set; }

    public string HomeCity { get; set; }

    public string HomeState { get; set; }

    public string HomePostalCode { get; set; }

    public string HomeCountry { get; set; }

    public string HomePhone { get; set; }

    public string HomeFax { get; set; }

    public string HomeEmail { get; set; }

    public string JobTitle { get; set; }

    public string MaritalStatus { get; set; }

    public string SpouseName { get; set; }

    public string College { get; set; }

    public string ClassYear { get; set; }

    public string PreferredClassYear { get; set; }

    public string Major1 { get; set; }

    public string Major2 { get; set; }

    public string ShareName { get; set; }

    public string ShareAddress { get; set; }

    public string Gender { get; set; }

    public string GradDate { get; set; }

    public string Email { get; set; }

    public string grad_student { get; set; }

    public string Barcode { get; set; }

    public string AD_Username { get; set; }

    public Nullable<int> show_pic { get; set; }

    public Nullable<int> preferred_photo { get; set; }

    public string Country { get; set; }

    public string Major2Description { get; set; }

    public string Major1Description { get; set; }

}

}
