//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordon360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChapelSummary
    {
        public int ID { get; set; }
        public string TermCD { get; set; }
        public string BarCode { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        public Nullable<int> Exception { get; set; }
        public string Married { get; set; }
        public Nullable<decimal> CreditHrs { get; set; }
        public string GEO { get; set; }
        public string Commuter { get; set; }
        public string GradFlag { get; set; }
        public Nullable<int> Required { get; set; }
        public Nullable<int> Attended { get; set; }
        public Nullable<System.DateTime> DeferredDate { get; set; }
        public Nullable<System.DateTime> WithdrawnDate { get; set; }
        public Nullable<System.DateTime> GraduatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Waived { get; set; }
        public string WaivedBy { get; set; }
        public Nullable<System.DateTime> WaivedDate { get; set; }
        public string Basis { get; set; }
        public string Defaulted { get; set; }
        public string Status { get; set; }
    }
}
