//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordon360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clifton_Strengths
    {
        public int ID_NUM { get; set; }
        public string ACCESS_CODE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DTE_COMPLETED { get; set; }
        public string THEME_1 { get; set; }
        public string THEME_2 { get; set; }
        public string THEME_3 { get; set; }
        public string THEME_4 { get; set; }
        public string THEME_5 { get; set; }
    }
}
