
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gordon360.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CM_SESSION_MSTR
{

    public string SESS_CDE { get; set; }

    public string SESS_DESC { get; set; }

    public Nullable<System.DateTime> SESS_BEGN_DTE { get; set; }

    public Nullable<System.DateTime> SESS_END_DTE { get; set; }

    public string YRTRM_CDE_2 { get; set; }

    public string YRTRM_CDE_4 { get; set; }

}

}
