
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gordon360.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CUSTOM_PROFILE
{

    public string username { get; set; }

    public string facebook { get; set; }

    public string twitter { get; set; }

    public string instagram { get; set; }

    public string linkedin { get; set; }

}

}
