
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gordon360.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Dining_Mealplans
{

    public string Meal_Plan_Description { get; set; }

    public string Meal_Plan_Type { get; set; }

    public string Meal_Plan_ID { get; set; }

    public Nullable<int> Meal_Plan_Initial_Balance { get; set; }

}

}
