
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gordon360.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DiningInfo
{

    public int StudentId { get; set; }

    public string SessionCode { get; set; }

    public string ChoiceDescription { get; set; }

    public string PlanDescriptions { get; set; }

    public string PlanId { get; set; }

    public Nullable<int> InitialBalance { get; set; }

    public string PlanType { get; set; }

}

}
