//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordon360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyContact
    {
        public int APPID { get; set; }
        public string AD_Username { get; set; }
        public int SEQ_NUM { get; set; }
        public int ID_NUM { get; set; }
        public Nullable<int> ID_NUM_EMRG_CNTCT { get; set; }
        public string prefix { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string suffix { get; set; }
        public string HomePhone { get; set; }
        public string HomeExt { get; set; }
        public string WorkPhone { get; set; }
        public string WorkExr { get; set; }
        public string MobilePhone { get; set; }
        public string MobileExt { get; set; }
        public string notes { get; set; }
        public string EmailAddress { get; set; }
        public string HomeAddrCode { get; set; }
        public string WorkAddrCode { get; set; }
        public string MobileAddrCode { get; set; }
        public string EmailAddrCode { get; set; }
        public string AddressAddrCode { get; set; }
        public string relationship { get; set; }
        public int EMRG_PRIORITY { get; set; }
        public string addr_1 { get; set; }
        public string addr_2 { get; set; }
        public string city { get; set; }
        public string EMRG_STATE { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public byte[] ApprowVersion { get; set; }
        public string UserName { get; set; }
        public string JobName { get; set; }
        public Nullable<System.DateTime> JobTime { get; set; }
    }
}
