
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gordon360.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FacStaff
{

    public string ID { get; set; }

    public string Title { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string Suffix { get; set; }

    public string MaidenName { get; set; }

    public string Nickname { get; set; }

    public string OnCampusDepartment { get; set; }

    public string OnCampusBuilding { get; set; }

    public string OnCampusRoom { get; set; }

    public string OnCampusPhone { get; set; }

    public string OnCampusPrivatePhone { get; set; }

    public string OnCampusFax { get; set; }

    public string HomeStreet1 { get; set; }

    public string HomeStreet2 { get; set; }

    public string HomeCity { get; set; }

    public string HomeState { get; set; }

    public string HomePostalCode { get; set; }

    public string HomeCountry { get; set; }

    public string HomePhone { get; set; }

    public string HomeFax { get; set; }

    public string KeepPrivate { get; set; }

    public string JobTitle { get; set; }

    public string SpouseName { get; set; }

    public string Dept { get; set; }

    public string Barcode { get; set; }

    public string Gender { get; set; }

    public string Email { get; set; }

    public string Type { get; set; }

    public string AD_Username { get; set; }

    public string office_hours { get; set; }

    public Nullable<int> preferred_photo { get; set; }

    public Nullable<int> show_pic { get; set; }

    public string BuildingDescription { get; set; }

    public string Country { get; set; }

}

}
