//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordon360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graduation
    {
        public int ID_NUM { get; set; }
        public string WHEN_GRAD { get; set; }
        public string HAS_GRADUATED { get; set; }
    }
}
