//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordon360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Health_Question
    {
        public string Question { get; set; }
        public string YesPrompt { get; set; }
        public string NoPrompt { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
