//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordon360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Housing_HallChoices
    {
        public int HousingAppID { get; set; }
        public int Ranking { get; set; }
        public string HallName { get; set; }
    
        public virtual Housing_Applications Housing_Applications { get; set; }
    }
}
