
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gordon360.Models
{

using System;
    using System.Collections.Generic;
    
public partial class JENZ_ACT_CLUB_DEF
{

    public string ACT_CDE { get; set; }

    public string ACT_DESC { get; set; }

    public string ACT_TYPE { get; set; }

    public string ACT_TYPE_DESC { get; set; }

    public int VP_IM { get; set; }

    public int VP_CC { get; set; }

    public int VP_LS { get; set; }

    public int VP_LW { get; set; }

}

}
