//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordon360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mailboxes
    {
        public int BoxId { get; set; }
        public string BoxNo { get; set; }
        public string Combination { get; set; }
        public string Type { get; set; }
        public Nullable<int> HolderAccountId { get; set; }
    }
}
