
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gordon360.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MEMBERSHIP
{

    public int MEMBERSHIP_ID { get; set; }

    public string ACT_CDE { get; set; }

    public string SESS_CDE { get; set; }

    public int ID_NUM { get; set; }

    public string PART_CDE { get; set; }

    public System.DateTime BEGIN_DTE { get; set; }

    public Nullable<System.DateTime> END_DTE { get; set; }

    public string COMMENT_TXT { get; set; }

    public string USER_NAME { get; set; }

    public string JOB_NAME { get; set; }

    public Nullable<System.DateTime> JOB_TIME { get; set; }

    public Nullable<bool> GRP_ADMIN { get; set; }

    public Nullable<bool> PRIVACY { get; set; }

}

}
