//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordon360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paid_shifts
    {
        public int ID { get; set; }
        public int ID_NUM { get; set; }
        public int eml { get; set; }
        public decimal hourly_rate { get; set; }
        public decimal regular_hours_worked { get; set; }
        public decimal ot_hours_worked { get; set; }
        public decimal ws_hours_worked { get; set; }
        public decimal wsot_hours_worked { get; set; }
        public int pay_period_id { get; set; }
        public string cost_code { get; set; }
        public System.DateTime datetime_entered { get; set; }
    }
}
