//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordon360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomAssign
    {
        public string SESS_CDE { get; set; }
        public string BLDG_LOC_CDE { get; set; }
        public string BLDG_CDE { get; set; }
        public string ROOM_CDE { get; set; }
        public int ROOM_SLOT_NUM { get; set; }
        public Nullable<int> ID_NUM { get; set; }
        public string ROOM_TYPE { get; set; }
        public string ROOM_ASSIGN_STS { get; set; }
        public Nullable<System.DateTime> ASSIGN_DTE { get; set; }
    }
}
