
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gordon360.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SCHEDULE
{
        public int SCHD_ID { get; set; }

        public int ID_NUM { get; set; }

        public System.DateTime BEGIN_DTE { get; set; }

        public System.DateTime END_DTE { get; set; }

        public string TITLE { get; set; }

        public string DSCRPT_TXT { get; set; }
        
}

}