//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordon360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_Control
    {
        public int IsSchedulePrivate { get; set; }
        public Nullable<System.DateTime> ModifiedTimeStamp { get; set; }
        public string Description { get; set; }
        public string gordon_id { get; set; }
    }
}
