
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gordon360.Models
{

using System;
    using System.Collections.Generic;
    
public partial class student_timesheets
{

    public int ID { get; set; }

    public int ID_NUM { get; set; }

    public int eml { get; set; }

    public string eml_description { get; set; }

    public System.DateTime shift_start_datetime { get; set; }

    public System.DateTime shift_end_datetime { get; set; }

    public decimal hourly_rate { get; set; }

    public decimal hours_worked { get; set; }

    public int supervisor { get; set; }

    public int comp_supervisor { get; set; }

    public string status { get; set; }

    public Nullable<int> submitted_to { get; set; }

    public string shift_notes { get; set; }

    public string comments { get; set; }

    public Nullable<System.DateTime> pay_week_date { get; set; }

    public Nullable<System.DateTime> pay_period_date { get; set; }

    public Nullable<int> pay_period_id { get; set; }

    public string last_changed_by { get; set; }

    public System.DateTime datetime_entered { get; set; }

}

}
