//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordon360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheets_Clock_In_Out
    {
        public int ID_Num { get; set; }
        public Nullable<bool> CurrentState { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
