//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordon360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transit_Rides
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transit_Rides()
        {
            this.Transit_Requests = new HashSet<Transit_Requests>();
        }
    
        public System.DateTime transaction_datetime { get; set; }
        public int ride_id { get; set; }
        public string driver_username { get; set; }
        public int max_capacity { get; set; }
        public string origin { get; set; }
        public string destination { get; set; }
        public System.DateTime departure_datetime { get; set; }
        public string driver_note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transit_Requests> Transit_Requests { get; set; }
    }
}
