// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.Gordon360;

[Table("ActivityType", Schema = "RecIM")]
public partial class ActivityType
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string Description { get; set; }

    [InverseProperty("Type")]
    public virtual ICollection<Activity> Activity { get; set; } = new List<Activity>();
}