# # # # # # # # #
# Configuration #
# # # # # # # # #

# Membership
# Activity to use for testing
activity_code = 'AJG'
# Id number to use for testing
random_id_number = 50153295
# Session to use for testing
session_code = '201501'
# Participation Code that correspond to member:
member_positions = ['MEMBR', 'GUEST', 'PART']
# Date
begin_date = '06/10/2016'
end_date = '07/16/2016'
date = '07/06/2016'
# Comments
comments = 'Generated by the Raymond Test Suite. IGNORE'

#Event or Type ID used for events testing
Event_OR_Type_ID = '10'
# Participation Codes that correspond to leaders:
leadership_positions = ['CAPT','CODIR','CORD','DIREC','PRES','VICEC','VICEP']

# Profile image
# Profile picture for testing
FILE_PATH = './profile.jpg'
FILE_NAME = ''

# API 
hostURL = 'https://360ApiTrain.gordon.edu/'









