// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Gordon360.Models.StudentTimesheets;

namespace Gordon360.Database.StudentTimesheets
{
    public partial class StudentTimesheetsContext : DbContext
    {
        public StudentTimesheetsContext()
        {
        }

        public StudentTimesheetsContext(DbContextOptions<StudentTimesheetsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<student_timesheets> student_timesheets { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=admintrainsql.gordon.edu;Initial Catalog=StudentTimesheets;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<student_timesheets>(entity =>
            {
                entity.Property(e => e.ID_NUM).HasComment("Gordon ID Number");

                entity.Property(e => e.eml).HasComment("a job's unique id number");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}