// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Table("FoundGuest", Schema = "LostAndFound")]
public partial class FoundGuest
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string firstName { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string lastName { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string phoneNumber { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string emailAddress { get; set; }

    [InverseProperty("foundByGuest")]
    public virtual ICollection<FoundItems> FoundItemsfoundByGuest { get; set; } = new List<FoundItems>();

    [InverseProperty("guestOwner")]
    public virtual ICollection<FoundItems> FoundItemsguestOwner { get; set; } = new List<FoundItems>();
}