// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gordon360.Models.CCT;

[Keyless]
public partial class MissingItemData
{
    public int ID { get; set; }

    [Required]
    [StringLength(63)]
    [Unicode(false)]
    public string submitterID { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string matchingFoundID { get; set; }

    public bool forGuest { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string category { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string colors { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string brand { get; set; }

    [Required]
    [StringLength(511)]
    [Unicode(false)]
    public string description { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string locationLost { get; set; }

    public bool stolen { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string stolenDesc { get; set; }

    [Column(TypeName = "date")]
    public DateTime dateLost { get; set; }

    [Column(TypeName = "date")]
    public DateTime dateCreated { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string status { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string submitterUsername { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string firstName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string lastName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string email { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string phone { get; set; }
}